"""init

Revision ID: 4a536e203a04
Revises: 
Create Date: 2026-06-28 09:57:42.332817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a536e203a04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('placement', sa.String(length=50), nullable=False),
    sa.Column('adsense_slot_id', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_articles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_slug', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_ne', sa.Text(), nullable=False),
    sa.Column('full_text_en', sa.Text(), nullable=False),
    sa.Column('full_text_ne', sa.Text(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_articles_category_slug'), 'legal_articles', ['category_slug'], unique=False)
    op.create_table('legal_categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=100), nullable=False),
    sa.Column('name_ne', sa.String(length=100), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('description_ne', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('legal_news_updates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('summary_en', sa.Text(), nullable=False),
    sa.Column('summary_ne', sa.Text(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('office_locations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('office_type', sa.String(length=50), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('name_ne', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('category_slug', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', 'LAWYER', name='userrole'), nullable=False),
    sa.Column('preferred_language', sa.String(length=5), nullable=False),
    sa.Column('accessibility_mode', sa.Enum('STANDARD', 'SENIOR', 'STUDENT', name='accessibilitymode'), nullable=False),
    sa.Column('subscription_plan', sa.Enum('FREE', 'PREMIUM', name='subscriptionplan'), nullable=False),
    sa.Column('subscription_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('badges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('badge_code', sa.String(length=50), nullable=False),
    sa.Column('awarded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('legal_category', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_type', sa.Enum('POLICE', 'CYBER_BUREAU', 'MUNICIPALITY', 'CONSUMER', 'OFFICE_GRIEVANCE', name='complainttype'), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=False),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_reminders',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('reminder_type', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lawyer_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('specialization', sa.String(length=100), nullable=False),
    sa.Column('bio_en', sa.Text(), nullable=False),
    sa.Column('bio_ne', sa.Text(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=False),
    sa.Column('consultation_fee_npr', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_documents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'EXPLAINED', 'FAILED', name='documentstatus'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('explanation_ne', sa.Text(), nullable=True),
    sa.Column('explanation_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('ESEWA', 'KHALTI', 'STRIPE', 'FONEPAY', name='paymentprovider'), nullable=False),
    sa.Column('transaction_id', sa.String(length=120), nullable=False),
    sa.Column('provider_reference_id', sa.String(length=120), nullable=True),
    sa.Column('amount_npr', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'AWAITING_REVIEW', 'SUCCESS', 'FAILED', 'REJECTED', 'CANCELLED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('plan_purchased', sa.String(length=50), nullable=False),
    sa.Column('subscription_expiry_date', sa.DateTime(), nullable=True),
    sa.Column('raw_callback_payload', sa.String(length=4000), nullable=True),
    sa.Column('user_submitted_reference', sa.String(length=120), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('admin_notes', sa.String(length=1000), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_transaction_id'), 'payments', ['transaction_id'], unique=True)
    op.create_table('quiz_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('quiz_id', sa.String(length=36), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scam_checks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_text', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consultation_bookings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('lawyer_id', sa.String(length=36), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['lawyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultation_bookings')
    op.drop_table('chat_messages')
    op.drop_table('scam_checks')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_payments_transaction_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('legal_documents')
    op.drop_table('lawyer_profiles')
    op.drop_table('compliance_reminders')
    op.drop_table('complaints')
    op.drop_table('chat_sessions')
    op.drop_table('badges')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('quizzes')
    op.drop_table('office_locations')
    op.drop_table('legal_news_updates')
    op.drop_table('legal_categories')
    op.drop_index(op.f('ix_legal_articles_category_slug'), table_name='legal_articles')
    op.drop_table('legal_articles')
    op.drop_table('advertisements')
    # ### end Alembic commands ###
