"""add law library + gamification

Revision ID: f3637fe482d3
Revises: 4a536e203a04
Create Date: 2026-07-04 12:44:54.481716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f3637fe482d3'
down_revision: Union[str, None] = '4a536e203a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laws',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('category_slug', sa.String(length=50), nullable=False),
    sa.Column('short_description_en', sa.Text(), nullable=False),
    sa.Column('short_description_ne', sa.Text(), nullable=False),
    sa.Column('year_bs', sa.String(length=10), nullable=True),
    sa.Column('source_reference', sa.String(length=255), nullable=False),
    sa.Column('cover_icon', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='lawstatus'), nullable=False),
    sa.Column('publish_at', sa.DateTime(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_laws_category_slug'), 'laws', ['category_slug'], unique=False)
    op.create_index(op.f('ix_laws_slug'), 'laws', ['slug'], unique=True)
    op.create_table('law_chapters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('law_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='lawstatus'), nullable=False),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_chapters_law_id'), 'law_chapters', ['law_id'], unique=False)
    op.create_table('study_streak_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('study_date', sa.String(length=10), nullable=False),
    sa.Column('sections_completed', sa.Integer(), nullable=False),
    sa.Column('xp_earned', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'study_date', name='uq_user_study_date')
    )
    op.create_index(op.f('ix_study_streak_logs_user_id'), 'study_streak_logs', ['user_id'], unique=False)
    op.create_table('user_learning_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('xp_total', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=30), nullable=False),
    sa.Column('current_streak_days', sa.Integer(), nullable=False),
    sa.Column('longest_streak_days', sa.Integer(), nullable=False),
    sa.Column('last_activity_date', sa.String(length=10), nullable=True),
    sa.Column('daily_goal_sections', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('law_sections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('chapter_id', sa.String(length=36), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('title_ne', sa.String(length=255), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('text_ne', sa.Text(), nullable=False),
    sa.Column('explanation_en', sa.Text(), nullable=False),
    sa.Column('explanation_ne', sa.Text(), nullable=False),
    sa.Column('examples', sa.JSON(), nullable=False),
    sa.Column('related_law_section_ids', sa.JSON(), nullable=False),
    sa.Column('important_notes_en', sa.Text(), nullable=False),
    sa.Column('important_notes_ne', sa.Text(), nullable=False),
    sa.Column('audio_url_en', sa.String(length=500), nullable=True),
    sa.Column('audio_url_ne', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='lawstatus'), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['law_chapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_sections_chapter_id'), 'law_sections', ['chapter_id'], unique=False)
    op.create_table('law_bookmarks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['law_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_section_bookmark')
    )
    op.create_index(op.f('ix_law_bookmarks_user_id'), 'law_bookmarks', ['user_id'], unique=False)
    op.create_table('law_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['law_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_notes_user_id'), 'law_notes', ['user_id'], unique=False)
    op.create_table('user_section_progress',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('section_id', sa.String(length=36), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['law_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'section_id', name='uq_user_section_progress')
    )
    op.create_index(op.f('ix_user_section_progress_user_id'), 'user_section_progress', ['user_id'], unique=False)
    op.alter_column('voice_usage', 'seconds_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('voice_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_usage', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('voice_usage', 'seconds_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_user_section_progress_user_id'), table_name='user_section_progress')
    op.drop_table('user_section_progress')
    op.drop_index(op.f('ix_law_notes_user_id'), table_name='law_notes')
    op.drop_table('law_notes')
    op.drop_index(op.f('ix_law_bookmarks_user_id'), table_name='law_bookmarks')
    op.drop_table('law_bookmarks')
    op.drop_index(op.f('ix_law_sections_chapter_id'), table_name='law_sections')
    op.drop_table('law_sections')
    op.drop_table('user_learning_profiles')
    op.drop_index(op.f('ix_study_streak_logs_user_id'), table_name='study_streak_logs')
    op.drop_table('study_streak_logs')
    op.drop_index(op.f('ix_law_chapters_law_id'), table_name='law_chapters')
    op.drop_table('law_chapters')
    op.drop_index(op.f('ix_laws_slug'), table_name='laws')
    op.drop_index(op.f('ix_laws_category_slug'), table_name='laws')
    op.drop_table('laws')
    # ### end Alembic commands ###
